# Tell Travies we need a copy of a docker running
sudo: required
services:
  - docker

# Build our image using Dockerfile.dev
before_install:
  -  docker build -t konszwg/docker-react -f Dockerfile.dev .


#Tell Travis how to run our test suite
script:
  - docker run -e CI=true konszwg/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "react-docker" 
    env: "React-docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-954640356888"
    bucket_path: "react-docker"
    on:
      branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
